### ISSUE TITLE
Chrome width resize bug

### ISSUE THREAD

**Issue by evolutionxbox** [rachelandrew/gridbugs#16]
## Platform
MacBook Pro 15" - macOS 10.12.5 - Chrome 60.0.3112.113 (64bit)

## Description
Content will not reduce width inside a grid with fixed/fluid/fixed width columns when container is narrowed.

## Steps to reproduce

Create page with the following HTML/CSS.

```HTML
<div class="grid flf">
  <div class="element">Fixed</div>
  <div class="element">Fluid</div>
  <div class="element">Fixed</div>
</div>
```

```CSS
.grid {
  background: lightpink;
  display: grid;
  grid-template-rows: 200px;
  margin: 0 auto;
  width: 98vw;
}

.flf {
  grid-template-columns: 200px 1fr 200px;
}

.element {
  background: lightblue;
  color: #000;
  grid-row: 1;
  height: 200px;
  outline: 1px solid black;
  width: 200px;
  
  &:nth-child(2) {
    margin: auto;
  }
}
```

Widen, then narrow, the viewport and witness the content not resize with the container.

## Demo
See https://codepen.io/evolutionxbox/full/gxyvzB/

![image](https://user-images.githubusercontent.com/660368/30074253-bee758f4-9268-11e7-85a2-3f1909119cae.png)
