### ISSUE TITLE
Safari doesn't seem to support max-content in repeat()

### ISSUE THREAD

**Issue by simevidas** [rachelandrew/gridbugs#5]
The code:

```css
.grid {
  display: grid;
  grid-template-columns: repeat(4, max-content);
}
```

The demo: https://codepen.io/simevidas/pen/KvMVWw?editors=0100

***

In Chrome and Firefox, the 4 grid items are centered in in a single row, while in Safari for iOS 10.3.3, they're laid out vertically as if there is no grid layout. Afaik, all `<track-list>` values, including `max-content`, are supported in the `repeat()` notation.

As a workaround, switching from `max-content` to `auto` seems to work fine. If I'm reading the spec correctly, `auto` is like `max-content` with the exception that it allows tracks to shrink to a certain point, based on a specified `min-width`/`min-height` value.
