### ISSUE TITLE
Firefox, Edge don’t stretch `fit-content()` tracks by default

### ISSUE THREAD

**Issue by simevidas** [rachelandrew/gridbugs#9]
Code:

```css
.grid {
    display: grid;
    grid-template-columns: repeat(3, fit-content(100px));
}
```

Demo: https://codepen.io/simevidas/pen/LjLJgo?editors=0100

I’ve noticed that in Firefox and Edge 16 (the upcoming version with full Grid support), when you have a bunch of columns clamped with `fit-content()`, the columns don’t stretch when there is more space available in the grid container. In Chrome, they do.

This isn’t a big problem, since, when I’m restricting the max size with `fit-content()`, I don’t want the tracks to extend beyond this size, so I can just set `justify-content: start` to disable stretching explicitly.
